/* eslint quote-props: 0 */
module.exports = {
	'one-var': 0,
	'one-var-declaration-per-line': 0,
	'quote-props': ['error', 'as-needed', { keywords: true, unnecessary: false }],
	'wrap-iffe': 0,
	'global-require': 0,
	'no-case-declarations': 0,
	'prefer-destructuring': 0,
	'comma-dangle': ['error', 'only-multiline'],
	'indent': ['error', 'tab', { SwitchCase: 1 }],
	'prefer-const': 'warn',
	'camelcase': 'warn',
	'max-len': 0,
	'vars-on-top': 0,
	'func-names': 0,
	'no-script-url': 0,
	'no-shadow': 0,
	'no-tabs': 0,
	'no-continue': 0,
	'no-plusplus': 0,
	'no-multi-assign': 0,
	'no-underscore-dangle': 0,
	'no-mixed-operators': 0,
	'space-before-function-paren': 0,
	'arrow-parens': 0,
	'prefer-template': 0,
	'consistent-return': 0,
	'arrow-body-style': 0,
	'array-bracket-spacing': 0,
	'no-else-return': 0,
	'no-param-reassign': 0,
	'class-methods-use-this': 'warn',
	'no-unused-vars': ['error', { args: 'none' }],
	'object-curly-newline': ['error', { consistent: true }],
	'import/prefer-default-export': 0,
	'padded-blocks': ['error', 'never'],
	'semi': ['error', 'always'],
	'semi-spacing': ['error', { before: false, after: true }],
};
